import { randomUUID } from "node:crypto";
import { lstatSync } from "node:fs";
import { mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { discoverProjectTemplates, type DiscoveredTemplate } from "./project-templates.js";
import { safeProjectPath } from "./safe-path.js";

export interface TemplateSyncPreview {
  sourcePath: string;
  exportName: string;
  importPath: string;
  metadata: DiscoveredTemplate["metadata"];
}

export interface GeneratedRegistryChange {
  path: string;
  action: "create" | "update";
  before?: string;
  after: string;
}

export interface SyncTemplatesOptions {
  cwd?: string;
  check?: boolean;
  timeoutMs?: number;
  /** @internal Failure injection for transaction verification. */
  renameFile?: (from: string, to: string) => Promise<void>;
  /** @internal Failure injection for post-commit cleanup verification. */
  unlinkFile?: (path: string) => Promise<void>;
}

export interface SyncTemplatesResult {
  changed: boolean;
  files: readonly string[];
  templates: readonly string[];
  warnings: readonly string[];
}

const GENERATED_NOTICE = "// Generated by `vanillasky sync`. Do not edit.\n";

function browserSource(templates: readonly DiscoveredTemplate[]): string {
  const imports = templates.map(({ exportName, importPath }, index) => exportName === "default"
    ? `import template${index} from ${JSON.stringify(importPath)};`
    : `import { ${exportName} as template${index} } from ${JSON.stringify(importPath)};`);
  const names = templates.map((_, index) => `template${index}`);
  return [
    GENERATED_NOTICE.trimEnd(),
    'import { createTemplateRegistry } from "@vanillaskyai/video/templates";',
    ...imports,
    "",
    `export const definitions = [${names.join(", ")}];`,
    "export const templates = createTemplateRegistry({ definitions });",
    "",
  ].join("\n");
}

function serverSource(templates: readonly DiscoveredTemplate[]): string {
  const metadata = JSON.stringify(templates.map(({ metadata: value }) => value), null, 2);
  return [
    GENERATED_NOTICE.trimEnd(),
    'import { createServerTemplateRegistry } from "@vanillaskyai/video/server";',
    'import type { ServerTemplateMetadata } from "@vanillaskyai/video/server";',
    "",
    `const templateMetadata: ServerTemplateMetadata[] = ${metadata};`,
    "export const templates = createServerTemplateRegistry({ templates: templateMetadata });",
    "",
  ].join("\n");
}

async function currentSource(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

interface PlannedOutput {
  path: string;
  source: string;
  temporary: string;
  backup: string;
  hadPrevious: boolean;
  backupCreated: boolean;
  installed: boolean;
}

export interface GeneratedTemplateStatus {
  browser: { path: "vanillasky/index.ts"; current: boolean };
  server: { path: "vanillasky/server.ts"; current: boolean };
  current: boolean;
  stale: readonly string[];
}

function generatedOutputs(cwd: string, discovered: readonly DiscoveredTemplate[]): readonly { path: string; source: string }[] {
  const vanillaskyDirectory = join(cwd, "vanillasky");
  return [
    { path: join(vanillaskyDirectory, "index.ts"), source: browserSource(discovered) },
    { path: join(vanillaskyDirectory, "server.ts"), source: serverSource(discovered) },
  ];
}

export async function previewTemplateSync(options: {
  cwd: string;
  templates: readonly TemplateSyncPreview[];
}): Promise<GeneratedRegistryChange[]> {
  const cwd = resolve(options.cwd);
  const replacements = new Set(options.templates.map(({ sourcePath }) => safeProjectPath(cwd, sourcePath)));
  const installed = await discoverProjectTemplates(cwd, { excludeSourcePaths: [...replacements] });
  const proposed: DiscoveredTemplate[] = options.templates.map((template) => ({
    ...template,
    filePath: safeProjectPath(cwd, template.sourcePath),
  }));
  const templates = [...installed, ...proposed]
    .sort((left, right) => left.filePath.localeCompare(right.filePath));
  const byId = new Map<string, DiscoveredTemplate>();
  for (const template of templates) {
    const duplicate = byId.get(template.metadata.id);
    if (duplicate) {
      throw new Error(
        `Duplicate template id ${JSON.stringify(template.metadata.id)} in ${relative(cwd, duplicate.filePath)} and ${relative(cwd, template.filePath)}`,
      );
    }
    byId.set(template.metadata.id, template);
  }

  const changes: GeneratedRegistryChange[] = [];
  for (const output of generatedOutputs(cwd, templates)) {
    safeProjectPath(cwd, output.path);
    const before = await currentSource(output.path);
    if (before === output.source) continue;
    changes.push({
      path: relative(cwd, output.path),
      action: before == null ? "create" : "update",
      ...(before == null ? {} : { before }),
      after: output.source,
    });
  }
  return changes;
}

export async function inspectGeneratedTemplateStatus(
  cwd: string,
  discovered: readonly DiscoveredTemplate[],
): Promise<GeneratedTemplateStatus> {
  const root = resolve(cwd);
  const stale: string[] = [];
  for (const output of generatedOutputs(root, discovered)) {
    safeProjectPath(root, output.path);
    if (await currentSource(output.path) !== output.source) stale.push(relative(root, output.path));
  }
  return {
    browser: { path: "vanillasky/index.ts", current: !stale.includes("vanillasky/index.ts") },
    server: { path: "vanillasky/server.ts", current: !stale.includes("vanillasky/server.ts") },
    current: stale.length === 0,
    stale,
  };
}

async function unlinkIfPresent(path: string): Promise<void> {
  try {
    await unlink(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

async function writeStagedFile(path: string, source: string): Promise<void> {
  const handle = await open(path, "wx", 0o644);
  try {
    await handle.writeFile(source, "utf8");
    await handle.sync();
  } finally {
    await handle.close();
  }
}

async function writeOutputsTransactionally(
  cwd: string,
  outputs: readonly { path: string; source: string }[],
  renameFile: (from: string, to: string) => Promise<void>,
  unlinkFile: (path: string) => Promise<void>,
): Promise<string[]> {
  const planned: PlannedOutput[] = outputs.map((output) => {
    safeProjectPath(cwd, output.path);
    const nonce = randomUUID();
    const directory = dirname(output.path);
    return {
      ...output,
      temporary: join(directory, `.${basename(output.path)}.vanillasky-stage-${nonce}`),
      backup: join(directory, `.${basename(output.path)}.vanillasky-backup-${nonce}`),
      hadPrevious: lstatSync(output.path, { throwIfNoEntry: false }) != null,
      backupCreated: false,
      installed: false,
    };
  });

  try {
    for (const output of planned) {
      safeProjectPath(cwd, output.temporary);
      safeProjectPath(cwd, output.backup);
      await writeStagedFile(output.temporary, output.source);
    }

    for (const output of planned) {
      safeProjectPath(cwd, output.path);
      if (output.hadPrevious) {
        await renameFile(output.path, output.backup);
        output.backupCreated = true;
      }
      await renameFile(output.temporary, output.path);
      output.installed = true;
    }
  } catch (error) {
    for (const output of [...planned].reverse()) {
      if (output.installed) await unlinkIfPresent(output.path);
      if (output.backupCreated) await rename(output.backup, output.path);
      await unlinkIfPresent(output.temporary);
    }
    throw error;
  }

  const warnings: string[] = [];
  for (const output of planned) {
    try {
      await unlinkFile(output.backup);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        warnings.push(`Could not remove transaction backup: ${relative(cwd, output.backup)}`);
      }
    }
  }
  return warnings;
}

export async function syncTemplates(options: SyncTemplatesOptions = {}): Promise<SyncTemplatesResult> {
  const cwd = resolve(options.cwd ?? process.cwd());
  const vanillaskyDirectory = join(cwd, "vanillasky");
  const discovered = await discoverProjectTemplates(cwd, { timeoutMs: options.timeoutMs });

  const outputs = generatedOutputs(cwd, discovered);
  for (const output of outputs) safeProjectPath(cwd, output.path);
  const drifted: string[] = [];
  let warnings: string[] = [];
  for (const output of outputs) {
    if (await currentSource(output.path) !== output.source) drifted.push(relative(cwd, output.path));
  }
  if (options.check && drifted.length > 0) {
    throw new Error(`Generated template files are out of date: ${drifted.join(", ")}. Run \`vanillasky sync\`.`);
  }
  if (!options.check && drifted.length > 0) {
    await mkdir(vanillaskyDirectory, { recursive: true });
    const changedOutputs = outputs.filter((output) => drifted.includes(relative(cwd, output.path)));
    for (const output of changedOutputs) safeProjectPath(cwd, output.path);
    warnings = await writeOutputsTransactionally(cwd, changedOutputs, options.renameFile ?? rename, options.unlinkFile ?? unlink);
  }
  return {
    changed: drifted.length > 0,
    files: drifted,
    templates: discovered.map(({ metadata }) => metadata.id),
    warnings,
  };
}
