/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run `npm run catalog:sync`.
 */
import type { ComponentType } from "react";
import type { SceneTemplateProps } from "./types.js";

export type BuiltinTemplateModule = { default: ComponentType<SceneTemplateProps> };

export const GENERATED_BUILTIN_TEMPLATE_LOADERS = {
  "media": () => import("../scene-templates/bg-media.js").then((module) => ({ default: module.BgMediaTemplate })),
  "reaction": () => import("../scene-templates/reaction.js").then((module) => ({ default: module.ReactionTemplate })),
  "confetti": () => import("../scene-templates/bg-confetti.js").then((module) => ({ default: module.BgConfettiTemplate })),
  "emojiBurst": () => import("../scene-templates/bg-emoji.js").then((module) => ({ default: module.BgEmojiTemplate })),
  "bigNumber": () => import("../scene-templates/chart-counter.js").then((module) => ({ default: module.ChartCounterTemplate })),
  "barChart": () => import("../scene-templates/chart-bar.js").then((module) => ({ default: module.ChartBarTemplate })),
  "progressRing": () => import("../scene-templates/chart-progress-ring.js").then((module) => ({ default: module.ChartProgressRingTemplate })),
  "phoneMockup": () => import("../scene-templates/showcase-phone.js").then((module) => ({ default: module.ShowcasePhoneTemplate })),
  "webMockup": () => import("../scene-templates/showcase-web.js").then((module) => ({ default: module.ShowcaseWebTemplate })),
  "codeEditor": () => import("../scene-templates/showcase-code.js").then((module) => ({ default: module.ShowcaseCodeTemplate })),
  "terminal": () => import("../scene-templates/showcase-terminal.js").then((module) => ({ default: module.ShowcaseTerminalTemplate })),
  "tweet": () => import("../scene-templates/social-tweet.js").then((module) => ({ default: module.SocialTweetTemplate })),
  "notification": () => import("../scene-templates/social-notification.js").then((module) => ({ default: module.SocialNotificationTemplate })),
  "chatMessenger": () => import("../scene-templates/social-conversation.js").then((module) => ({ default: module.SocialConversationTemplate })),
  "chatWhatsapp": () => import("../scene-templates/social-conversation.js").then((module) => ({ default: module.SocialConversationTemplate })),
  "milestone": () => import("../scene-templates/social-milestone.js").then((module) => ({ default: module.SocialMilestoneTemplate })),
  "reviewStack": () => import("../scene-templates/social-review-stack.js").then((module) => ({ default: module.SocialReviewStackTemplate })),
  "testimonial": () => import("../scene-templates/social-testimonial.js").then((module) => ({ default: module.SocialTestimonialTemplate })),
  "incomingCall": () => import("../scene-templates/incoming-call.js").then((module) => ({ default: module.IncomingCallTemplate })),
  "brandMessage": () => import("../scene-templates/brand-message.js").then((module) => ({ default: module.BrandMessageTemplate })),
  "promptInput": () => import("../scene-templates/prompt-input.js").then((module) => ({ default: module.PromptInputTemplate })),
  "beforeAfter": () => import("../scene-templates/infographic-before-after.js").then((module) => ({ default: module.InfographicBeforeAfterTemplate })),
  "tripleStats": () => import("../scene-templates/infographic-stat-row.js").then((module) => ({ default: module.InfographicStatRowTemplate })),
  "problemSolution": () => import("../scene-templates/infographic-problem-solution.js").then((module) => ({ default: module.InfographicProblemSolutionTemplate })),
  "cardList": () => import("../scene-templates/infographic-feature-list.js").then((module) => ({ default: module.InfographicFeatureListTemplate })),
  "steps": () => import("../scene-templates/infographic-steps.js").then((module) => ({ default: module.InfographicStepsTemplate })),
  "ctaLogo": () => import("../scene-templates/cta-logo.js").then((module) => ({ default: module.CtaLogoTemplate })),
  "ctaMedia": () => import("../scene-templates/cta-media.js").then((module) => ({ default: module.CtaMediaTemplate })),
} satisfies Record<string, () => Promise<BuiltinTemplateModule>>;
