// Generated by `vanillasky sync`. Do not edit.
import { createTemplateRegistry } from "@vanillaskyai/video/templates";
import { activationLift as template0 } from "./templates/activation-lift";

export const definitions = [template0];
export const templates = createTemplateRegistry({ definitions });
