// Generated by `vanillasky sync`. Do not edit.
import { createServerTemplateRegistry } from "@vanillaskyai/video/server";
import type { ServerTemplateMetadata } from "@vanillaskyai/video/server";

const templateMetadata: ServerTemplateMetadata[] = [
  {
    "label": "Activation lift",
    "description": "A project-owned view of an activation metric before and after an improvement.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "id": "activationLift",
    "useWhen": "Use when the source contains an exact activation percentage before and after a change.",
    "avoidWhen": "Avoid when the source does not contain both grounded percentages.",
    "family": "Data & metrics",
    "minDuration": 4,
    "preferredDuration": 6,
    "schema": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "default": "Activation improved"
        },
        "previous": {
          "type": "number",
          "format": "grounded-stat",
          "minimum": 0,
          "maximum": 100,
          "default": 41
        },
        "current": {
          "type": "number",
          "format": "grounded-stat",
          "minimum": 0,
          "maximum": 100,
          "default": 58
        },
        "explanation": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120,
          "default": "Guided onboarding helped more users reach value."
        }
      },
      "required": [
        "title",
        "previous",
        "current",
        "explanation"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true
      }
    }
  }
];
export const templates = createServerTemplateRegistry({ templates: templateMetadata });
