#!/usr/bin/env tsx

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BUILTIN_TEMPLATE_MANIFEST,
  type BuiltinTemplateId,
} from "../src/visual-system/catalog/builtin-manifest.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const templatesDirectory = join(root, "src/visual-system/scene-templates");
const outputPath = join(root, "src/visual-system/catalog/catalog.generated.ts");
const loadersOutputPath = join(root, "src/visual-system/catalog/builtin-loaders.generated.ts");

const templateModules = {
  media: { file: "bg-media.tsx", component: "BgMediaTemplate" },
  reaction: { file: "reaction.tsx", component: "ReactionTemplate" },
  confetti: { file: "bg-confetti.tsx", component: "BgConfettiTemplate" },
  emojiBurst: { file: "bg-emoji.tsx", component: "BgEmojiTemplate" },
  bigNumber: { file: "chart-counter.tsx", component: "ChartCounterTemplate" },
  barChart: { file: "chart-bar.tsx", component: "ChartBarTemplate" },
  progressRing: { file: "chart-progress-ring.tsx", component: "ChartProgressRingTemplate" },
  phoneMockup: { file: "showcase-phone.tsx", component: "ShowcasePhoneTemplate" },
  webMockup: { file: "showcase-web.tsx", component: "ShowcaseWebTemplate" },
  codeEditor: { file: "showcase-code.tsx", component: "ShowcaseCodeTemplate" },
  terminal: { file: "showcase-terminal.tsx", component: "ShowcaseTerminalTemplate" },
  tweet: { file: "social-tweet.tsx", component: "SocialTweetTemplate" },
  notification: { file: "social-notification.tsx", component: "SocialNotificationTemplate" },
  chatMessenger: { file: "social-conversation.tsx", component: "SocialConversationTemplate" },
  chatWhatsapp: { file: "social-conversation.tsx", component: "SocialConversationTemplate" },
  milestone: { file: "social-milestone.tsx", component: "SocialMilestoneTemplate" },
  reviewStack: { file: "social-review-stack.tsx", component: "SocialReviewStackTemplate" },
  testimonial: { file: "social-testimonial.tsx", component: "SocialTestimonialTemplate" },
  incomingCall: { file: "incoming-call.tsx", component: "IncomingCallTemplate" },
  brandMessage: { file: "brand-message.tsx", component: "BrandMessageTemplate" },
  promptInput: { file: "prompt-input.tsx", component: "PromptInputTemplate" },
  beforeAfter: { file: "infographic-before-after.tsx", component: "InfographicBeforeAfterTemplate" },
  tripleStats: { file: "infographic-stat-row.tsx", component: "InfographicStatRowTemplate" },
  problemSolution: { file: "infographic-problem-solution.tsx", component: "InfographicProblemSolutionTemplate" },
  cardList: { file: "infographic-feature-list.tsx", component: "InfographicFeatureListTemplate" },
  steps: { file: "infographic-steps.tsx", component: "InfographicStepsTemplate" },
  ctaLogo: { file: "cta-logo.tsx", component: "CtaLogoTemplate" },
  ctaMedia: { file: "cta-media.tsx", component: "CtaMediaTemplate" },
} satisfies Record<BuiltinTemplateId, { file: string; component: string }>;

function renderGeneratedCatalog(): string {
  const catalog = BUILTIN_TEMPLATE_MANIFEST;
  const catalogIds = catalog.map(({ id }) => id).sort();
  const mappedIds = Object.keys(templateModules).sort();
  if (JSON.stringify(catalogIds) !== JSON.stringify(mappedIds)) {
    throw new Error("Built-in template source map does not match the compiled catalog");
  }
  for (const { file } of Object.values(templateModules)) {
    readFileSync(join(templatesDirectory, file), "utf8");
  }

  return `/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run \`npm run catalog:sync\`.
 */
import type { SceneTemplateMetadata } from "./catalog-types.js";

export const GENERATED_BUILTIN_TEMPLATE_CATALOG = ${JSON.stringify(catalog, null, 2)} as const satisfies readonly SceneTemplateMetadata[];
`;
}

function renderGeneratedLoaders(): string {
  const entries = Object.entries(templateModules).map(([id, { file, component }]) => {
    const modulePath = `../scene-templates/${file.replace(/\.tsx$/, ".js")}`;
    return `  ${JSON.stringify(id)}: () => import(${JSON.stringify(modulePath)}).then((module) => ({ default: module.${component} })),`;
  });
  return `/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run \`npm run catalog:sync\`.
 */
import type { ComponentType } from "react";
import type { SceneTemplateProps } from "./types.js";

export type BuiltinTemplateModule = { default: ComponentType<SceneTemplateProps> };

export const GENERATED_BUILTIN_TEMPLATE_LOADERS = {
${entries.join("\n")}
} satisfies Record<string, () => Promise<BuiltinTemplateModule>>;
`;
}

const generated = renderGeneratedCatalog();
const generatedLoaders = renderGeneratedLoaders();
if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  const currentLoaders = readFileSync(loadersOutputPath, "utf8");
  if (current !== generated || currentLoaders !== generatedLoaders) {
    throw new Error("Built-in catalog drifted; run npm run catalog:sync");
  }
} else {
  writeFileSync(outputPath, generated);
  writeFileSync(loadersOutputPath, generatedLoaders);
}
